In [146]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import datasets

In [147]:
iris = datasets.load_iris()

In [148]:
X = iris.data

In [149]:
X[:10,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [80]:
y = iris.target

array([0., 1., 2., 3.])

In [6]:
y[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
df = pd.DataFrame({"SepalLength":iris.data[:,0],"SepalWidth":iris.data[:,1],"PetalLength":iris.data[:,2],"PetalWidth":iris.data[:,3],"FlowerClass":iris.target})

In [73]:
df.head(10)

FlowerClass  PetalLength  PetalWidth  SepalLength  SepalWidth
0            0          1.4         0.2          5.1         3.5
1            0          1.4         0.2          4.9         3.0
2            0          1.3         0.2          4.7         3.2
3            0          1.5         0.2          4.6         3.1
4            0          1.4         0.2          5.0         3.6
5            0          1.7         0.4          5.4         3.9
6            0          1.4         0.3          4.6         3.4
7            0          1.5         0.2          5.0         3.4
8            0          1.4         0.2          4.4         2.9
9            0          1.5         0.1          4.9         3.1

In [113]:
pd.qcut(X[:,1],4,labels=False)

array([3, 1, 2, 2, 3, 3, 3, 3, 1, 2, 3, 3, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 2, 3, 1, 3, 3, 3, 2, 2, 3, 3, 3, 2, 2, 3, 2, 1, 3, 3, 0, 2, 3,
       3, 1, 3, 2, 3, 2, 2, 2, 2, 0, 0, 0, 2, 0, 1, 0, 0, 1, 0, 1, 1, 2,
       1, 0, 0, 0, 2, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 3, 2, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 2, 0, 1, 1, 1, 1, 0, 1, 0, 3,
       2, 0, 1, 0, 0, 2, 1, 3, 0, 0, 2, 0, 0, 0, 2, 2, 0, 1, 0, 1, 0, 3,
       0, 0, 0, 1, 3, 2, 1, 2, 2, 2, 0, 2, 2, 1, 0, 1, 3, 1])

In [82]:
np.unique()

array([0., 1., 2., 3.])

In [41]:
xy = np.column_stack((X,y))

In [42]:
xy[:4]

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ]])

In [47]:
np.unique(xy[:,0]).shape[0]/xy.shape[0]

0.23333333333333334

In [25]:
l = np.unique((np.where(xy[:,4]==0) and np.where(xy[:3]==3)))

In [26]:
l

array([1])

In [15]:
X[l,:][0].shape

(4,)

In [145]:
class NaiveBayesClassifier():
    """
    Naive bayes classifier that utilized the unique property of conditional independence to approximate probabilities
    Parameters:
        X: numpy array() with n x p columns, p generally < n
        y: numpy array() of labels(classes)
        priors: numpy array() of prior probabilities
        binning: boolean that determines whether to quantile bin continuous values, default is true.
       
    """
    def __init__(self,X,y):

        self.X = X
        self.y = y
        self.datamatrix = np.column_stack((X,y))
        self.classvals = {}

    def get_data(self,binning):
        
        """
        Prior prob P(Y) is the value at index 1 in data
        
        """
        if self.binning == True:
            for i in range(self.X.shape[1]):
                if (np.unique(self.X[:,i]).shape[0]/self.X.shape[0]) > 0.1:
                    self.X[:,i] = pd.qcut(self.X[:,i],4,labels=False)
                    
        self.classvals = {}
        classes = np.unique(self.y)
        for i in classes:
            classx = self.X[np.where(self.y == i),:][0]
            data = [classx,classx.shape[0]/self.y.shape[0]]
            self.classvals[i] = data
            
    def generate_probabilites(self):
        """
        generate posterior probabilities P(X|Y)
        """
        
    
        

In [141]:
m = NaiveBayesClassifier(X,y,True)

In [142]:
m.X

array([[0., 3., 0., 0.],
       [0., 1., 0., 0.],
       [0., 2., 0., 0.],
       [0., 2., 0., 0.],
       [0., 3., 0., 0.],
       [1., 3., 1., 1.],
       [0., 3., 0., 0.],
       [0., 3., 0., 0.],
       [0., 1., 0., 0.],
       [0., 2., 0., 0.],
       [1., 3., 0., 0.],
       [0., 3., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 3., 0., 0.],
       [1., 3., 0., 1.],
       [1., 3., 0., 1.],
       [0., 3., 0., 0.],
       [1., 3., 1., 0.],
       [0., 3., 0., 0.],
       [1., 3., 1., 0.],
       [0., 3., 0., 1.],
       [0., 3., 0., 0.],
       [0., 2., 1., 1.],
       [0., 3., 1., 0.],
       [0., 1., 0., 0.],
       [0., 3., 0., 1.],
       [1., 3., 0., 0.],
       [1., 3., 0., 0.],
       [0., 2., 0., 0.],
       [0., 2., 0., 0.],
       [1., 3., 0., 1.],
       [1., 3., 0., 0.],
       [1., 3., 0., 0.],
       [0., 2., 0., 0.],
       [0., 2., 0., 0.],
       [1., 3., 0., 0.],
       [0., 2., 0., 0.],
       [0., 1., 0., 0.],
       [0., 3., 0., 0.],


In [ ]:
m.classvals[0]