In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import datasets
import sys
sys.path.append('../tools')
import tools

# K Nearest Neighbors

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data

In [4]:
X[:10,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [5]:
y = iris.target

In [10]:
class KNN(): 
    """
        K nearest neighbor classifier. Assign a given vector to a class based on l2 distance
    """
    def __init__(self,X,y):
        
        self.X = X
        self.y = y
        
    def predict(self,k,pred):
        
        classes = []
        for i in range(pred.shape[0]):
            predic = pred[i,:]
            print(predic)
            nvec = self.X[i,:]
            yval = self.y[i]
            self.y = np.delete(self.y,i)
            self.X = np.delete(self.X, (i),axis=0)
            dist = tools.l2distance(self.X,predic)
            self.X = np.insert(self.X, i, nvec, 0) 
            indices = dist.argsort()[:k]
            classcounts = y[indices]
            self.y = np.insert(self.y,i,yval)
            print(classcounts)
            vals,counts = np.unique(classcounts,return_counts=True)
            ind=np.argmax(counts)
            classpick = vals[ind]
            classes.append(classpick)
            
        return np.array(classes)    

In [11]:
m = KNN(X,y)
predict = m.predict(3,m.X)

[5.1 3.5 1.4 0.2]
[0 0 0]
[4.9 3.  1.4 0.2]
[0 0 0]
[4.7 3.2 1.3 0.2]
[0 0 0]
[4.6 3.1 1.5 0.2]
[0 0 0]
[5.  3.6 1.4 0.2]
[0 0 0]
[5.4 3.9 1.7 0.4]
[0 0 0]
[4.6 3.4 1.4 0.3]
[0 0 0]
[5.  3.4 1.5 0.2]
[0 0 0]
[4.4 2.9 1.4 0.2]
[0 0 0]
[4.9 3.1 1.5 0.1]
[0 0 0]
[5.4 3.7 1.5 0.2]
[0 0 0]
[4.8 3.4 1.6 0.2]
[0 0 0]
[4.8 3.  1.4 0.1]
[0 0 0]
[4.3 3.  1.1 0.1]
[0 0 0]
[5.8 4.  1.2 0.2]
[0 0 0]
[5.7 4.4 1.5 0.4]
[0 0 0]
[5.4 3.9 1.3 0.4]
[0 0 0]
[5.1 3.5 1.4 0.3]
[0 0 0]
[5.7 3.8 1.7 0.3]
[0 0 0]
[5.1 3.8 1.5 0.3]
[0 0 0]
[5.4 3.4 1.7 0.2]
[0 0 0]
[5.1 3.7 1.5 0.4]
[0 0 0]
[4.6 3.6 1.  0.2]
[0 0 0]
[5.1 3.3 1.7 0.5]
[0 0 0]
[4.8 3.4 1.9 0.2]
[0 0 0]
[5.  3.  1.6 0.2]
[0 0 0]
[5.  3.4 1.6 0.4]
[0 0 0]
[5.2 3.5 1.5 0.2]
[0 0 0]
[5.2 3.4 1.4 0.2]
[0 0 0]
[4.7 3.2 1.6 0.2]
[0 0 0]
[4.8 3.1 1.6 0.2]
[0 0 0]
[5.4 3.4 1.5 0.4]
[0 0 0]
[5.2 4.1 1.5 0.1]
[0 0 0]
[5.5 4.2 1.4 0.2]
[0 0 0]
[4.9 3.1 1.5 0.1]
[0 0 0]
[5.  3.2 1.2 0.2]
[0 0 0]
[5.5 3.5 1.3 0.2]
[0 0 0]
[4.9 3.1 1.5 0.1]
[0 0 0]
[4.4 3.  1.3

In [12]:
np.sum(abs(y - predict))/y.shape[0]

0.04